<?xml version="1.0" encoding="UTF-8"?>
<testng-results ignored="0" total="4" passed="1" failed="1" skipped="2">
  <reporter-output>
  </reporter-output>
  <suite started-at="2021-04-26T15:58:40 IST" name="Suite" finished-at="2021-04-26T15:58:40 IST" duration-ms="92">
    <groups>
      <group name="select">
        <method signature="Dependency.select()[pri:0, instance:depedency.Dependency@346d61be]" name="select" class="depedency.Dependency"/>
      </group> <!-- select -->
      <group name="buyproduct">
        <method signature="Dependency.buyproduct()[pri:0, instance:depedency.Dependency@346d61be]" name="buyproduct" class="depedency.Dependency"/>
      </group> <!-- buyproduct -->
      <group name="searchproduct">
        <method signature="Dependency.searchproduct()[pri:0, instance:depedency.Dependency@346d61be]" name="searchproduct" class="depedency.Dependency"/>
      </group> <!-- searchproduct -->
      <group name="confirmemail">
        <method signature="Dependency.confirmemail()[pri:0, instance:depedency.Dependency@346d61be]" name="confirmemail" class="depedency.Dependency"/>
      </group> <!-- confirmemail -->
    </groups>
    <test started-at="2021-04-26T15:58:40 IST" name="Dependency" finished-at="2021-04-26T15:58:40 IST" duration-ms="92">
      <class name="depedency.Dependency">
        <test-method signature="searchproduct()[pri:0, instance:depedency.Dependency@346d61be]" started-at="2021-04-26T15:58:40 IST" name="searchproduct" finished-at="2021-04-26T15:58:40 IST" duration-ms="16" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- searchproduct -->
        <test-method signature="select()[pri:0, instance:depedency.Dependency@346d61be]" started-at="2021-04-26T15:58:40 IST" name="select" depends-on-groups="searchproduct" finished-at="2021-04-26T15:58:40 IST" duration-ms="4" status="FAIL">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[fail]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: fail
at org.testng.Assert.fail(Assert.java:97)
at depedency.Dependency.select(Dependency.java:18)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:564)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:584)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:172)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:804)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:145)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:770)
at org.testng.TestRunner.run(TestRunner.java:591)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:402)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:396)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:355)
at org.testng.SuiteRunner.run(SuiteRunner.java:304)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1180)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1102)
at org.testng.TestNG.runSuites(TestNG.java:1032)
at org.testng.TestNG.run(TestNG.java:1000)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- select -->
        <test-method signature="buyproduct()[pri:0, instance:depedency.Dependency@346d61be]" started-at="2021-04-26T15:58:40 IST" name="buyproduct" depends-on-groups="select" finished-at="2021-04-26T15:58:40 IST" duration-ms="0" status="SKIP">
          <exception class="java.lang.Throwable">
            <message>
              <![CDATA[Method Dependency.buyproduct()[pri:0, instance:depedency.Dependency@346d61be] depends on not successfully finished methods in group "select"]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.Throwable: Method Dependency.buyproduct()[pri:0, instance:depedency.Dependency@346d61be] depends on not successfully finished methods in group "select"
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:99)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:770)
at org.testng.TestRunner.run(TestRunner.java:591)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:402)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:396)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:355)
at org.testng.SuiteRunner.run(SuiteRunner.java:304)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1180)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1102)
at org.testng.TestNG.runSuites(TestNG.java:1032)
at org.testng.TestNG.run(TestNG.java:1000)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.Throwable -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- buyproduct -->
        <test-method signature="confirmemail()[pri:0, instance:depedency.Dependency@346d61be]" started-at="2021-04-26T15:58:40 IST" name="confirmemail" depends-on-groups="buyproduct" finished-at="2021-04-26T15:58:40 IST" duration-ms="0" status="SKIP">
          <exception class="java.lang.Throwable">
            <message>
              <![CDATA[Method Dependency.confirmemail()[pri:0, instance:depedency.Dependency@346d61be] depends on not successfully finished methods in group "buyproduct"]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.Throwable: Method Dependency.confirmemail()[pri:0, instance:depedency.Dependency@346d61be] depends on not successfully finished methods in group "buyproduct"
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:99)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:770)
at org.testng.TestRunner.run(TestRunner.java:591)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:402)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:396)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:355)
at org.testng.SuiteRunner.run(SuiteRunner.java:304)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1180)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1102)
at org.testng.TestNG.runSuites(TestNG.java:1032)
at org.testng.TestNG.run(TestNG.java:1000)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.Throwable -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- confirmemail -->
      </class> <!-- depedency.Dependency -->
    </test> <!-- Dependency -->
  </suite> <!-- Suite -->
</testng-results>
